### ISSUE TITLE
Parasite Population Size

### ISSUE THREAD

**Issue by weswong** [edwenger/genepi#12]
How do we control for parasite population size?

Say I want to induce a bottleneck, this would be controlled by ability to successfully transmit to the human, am I correct?

**Comment by weswong** [comment]
Need to figure out how to correlate observed (real) Ne with model Ne

**Comment by edwenger** [comment]
Change functional form of vectorial capacity at node.
The few examples now have it as a sinusoid with no long-duration increases/decreases beyond the annual seasonality, but the model accepts arbitrary functional forms.

**Comment by weswong** [comment]
Makes sense. Population size of parasite will be limited by the vectorial capacity...this on its own should result in some equillibrium right? 

Hmm to make it relate to real data, would need to determine relationship between vectorial capacity and Ne.
