### ISSUE TITLE
GERMLINE executable missing?

### ISSUE THREAD

**Issue by weswong** [edwenger/genepi#9]
Just updated to latest version and tested the run_simulation.py script. Getting an error where it says:
GERMLINE executable not found at /Users/wesley/Wirth_Lab_Results/IDM/genepi/genepi/analysis/bin/germline"

Is this included somewhere in the folders in the github?

**Comment by edwenger** [comment]
No. But just added a readme in the analysis folder with link. Or you can disable that part of genome analysis from the example workflow?

**Comment by edwenger** [comment]
Available here: http://www.cs.columbia.edu/~gusev/germline/

**Comment by edwenger** [comment]
Edited example so user isn't confronted with crash before reading analysis docs. 8a482c6e75411bf0b6348627d56c687efb63c162
